# Generated by Django 3.1.5 on 2021-01-28 14:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='callinfo',
            name='id',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='id',
        ),
        migrations.RemoveField(
            model_name='direction',
            name='id',
        ),
        migrations.RemoveField(
            model_name='documents',
            name='id',
        ),
        migrations.RemoveField(
            model_name='studies',
            name='id',
        ),
        migrations.AlterField(
            model_name='callinfo',
            name='candidate',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='candidates.candidate'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='candidate',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='candidates.candidate'),
        ),
        migrations.AlterField(
            model_name='direction',
            name='candidate',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='candidates.candidate'),
        ),
        migrations.AlterField(
            model_name='documents',
            name='candidate',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='candidates.candidate'),
        ),
        migrations.AlterField(
            model_name='studies',
            name='candidate',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='candidates.candidate'),
        ),
    ]
