# Generated by Django 3.1.6 on 2021-03-03 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0002_auto_20210128_0842'),
    ]

    operations = [
        migrations.AddField(
            model_name='direction',
            name='suburb',
            field=models.CharField(default=None, max_length=70),
            preserve_default=False,
        ),
    ]
