# Generated by Django 3.1.6 on 2021-03-03 21:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0003_direction_suburb'),
    ]

    operations = [
        migrations.RenameField(
            model_name='direction',
            old_name='delegacion',
            new_name='delegation',
        ),
    ]
