# Generated by Django 3.1.6 on 2021-03-04 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0004_auto_20210303_1547'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='mobile_telephone',
            field=models.IntegerField(blank=True, help_text='Entry Mobile Telephone', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='telephone',
            field=models.IntegerField(help_text='Entry Telephone', max_length=10),
        ),
    ]
