# Generated by Django 3.1.6 on 2021-03-04 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0005_auto_20210303_1807'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='mobile_telephone',
            field=models.IntegerField(blank=True, help_text='Entry Mobile Telephone', null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='telephone',
            field=models.IntegerField(help_text='Entry Telephone'),
        ),
    ]
