# Generated by Django 3.1.6 on 2021-03-08 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0008_auto_20210305_1257'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='details',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='candidate',
            name='status',
            field=models.CharField(choices=[('PENDIENTE', 'PENDIENTE'), ('RECHAZADO', 'RECHAZADO'), ('ACEPTADO', 'ACEPTADO')], default='SIN_REVISAR', max_length=15),
        ),
    ]
