# Generated by Django 3.1.6 on 2021-03-08 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0009_auto_20210308_1422'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='status',
            field=models.CharField(choices=[('SIN_REVISAR', 'SIN_REVISAR'), ('PENDIENTE', 'PENDIENTE'), ('RECHAZADO', 'RECHAZADO'), ('ACEPTADO', 'ACEPTADO')], default='SIN_REVISAR', max_length=15),
        ),
    ]
