# Generated by Django 3.1.5 on 2021-01-27 23:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scholar', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scholarcoursesubject',
            name='assistances',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='scholar.assistance'),
            preserve_default=False,
        ),
    ]
