# Generated by Django 3.1.5 on 2021-01-27 23:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scholar', '0002_scholarcoursesubject_assistances'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scholarcoursesubject',
            name='assistances',
        ),
    ]
