# Generated by Django 3.1.5 on 2021-01-27 23:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scholar', '0003_remove_scholarcoursesubject_assistances'),
    ]

    operations = [
        migrations.AddField(
            model_name='scholarcoursesubject',
            name='assistances',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='scholar.assistance'),
        ),
    ]
