# Generated by Django 3.1.5 on 2021-01-29 00:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scholar', '0006_auto_20210128_1821'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scholarcoursesubject',
            name='assistances',
        ),
        migrations.AddField(
            model_name='assistance',
            name='scholar_course_subject',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='scholar.scholarcoursesubject'),
            preserve_default=False,
        ),
    ]
