# Generated by Django 3.1.5 on 2021-02-03 16:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('scholar', '0007_auto_20210128_1826'),
    ]

    operations = [
        migrations.CreateModel(
            name='Initial_Training',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hours', models.IntegerField()),
                ('end_date', models.DateField()),
                ('qualification', models.IntegerField()),
                ('status', models.BooleanField()),
                ('scholar', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='scholar.scholar')),
            ],
        ),
    ]
