# Generated by Django 3.1.5 on 2021-01-28 21:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='subjects',
        ),
        migrations.AddField(
            model_name='subject',
            name='course',
            field=models.ForeignKey(default=None, help_text='Entry subjects course', on_delete=django.db.models.deletion.CASCADE, to='course.course'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='campus',
            name='capacity',
            field=models.IntegerField(default=700, help_text='Entry capacity campu'),
        ),
        migrations.AlterField(
            model_name='campus',
            name='courses',
            field=models.ForeignKey(help_text='Entry courses campus', on_delete=django.db.models.deletion.CASCADE, to='course.course'),
        ),
        migrations.AlterField(
            model_name='campus',
            name='direction',
            field=models.CharField(help_text='Entry direction campus', max_length=255),
        ),
        migrations.AlterField(
            model_name='campus',
            name='name',
            field=models.CharField(help_text='Entry name campus', max_length=255),
        ),
        migrations.AlterField(
            model_name='campus',
            name='status',
            field=models.BooleanField(default=True, help_text='Entry status campus'),
        ),
        migrations.AlterField(
            model_name='campus',
            name='zone',
            field=models.OneToOneField(help_text='Entry zone campus', on_delete=django.db.models.deletion.CASCADE, to='course.zone'),
        ),
        migrations.AlterField(
            model_name='course',
            name='name',
            field=models.CharField(help_text='Entry name course', max_length=255),
        ),
        migrations.AlterField(
            model_name='course',
            name='status',
            field=models.BooleanField(default=False, help_text='Entry status course'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='name',
            field=models.CharField(help_text='Entry name subject', max_length=150),
        ),
        migrations.AlterField(
            model_name='subject',
            name='status',
            field=models.BooleanField(default=True, help_text='Entry status subject'),
        ),
        migrations.AlterField(
            model_name='zone',
            name='name',
            field=models.CharField(help_text='Entry name zone', max_length=50),
        ),
    ]
