# Generated by Django 3.1.5 on 2021-01-28 21:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_auto_20210128_1550'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='course',
        ),
        migrations.AddField(
            model_name='course',
            name='subjects',
            field=models.ForeignKey(default=1, help_text='Entry subjects course', on_delete=django.db.models.deletion.CASCADE, to='course.subject'),
            preserve_default=False,
        ),
    ]
