# Generated by Django 3.1.5 on 2021-01-28 21:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_auto_20210128_1551'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='subjects',
        ),
        migrations.AddField(
            model_name='subject',
            name='course',
            field=models.ForeignKey(default=None, help_text='Entry subjects course', on_delete=django.db.models.deletion.CASCADE, to='course.course'),
            preserve_default=False,
        ),
    ]
