# Generated by Django 3.1.5 on 2021-01-28 23:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0004_auto_20210128_1553'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campus',
            name='courses',
        ),
        migrations.AddField(
            model_name='course',
            name='campus',
            field=models.ForeignKey(default=None, help_text='Entry courses campus', on_delete=django.db.models.deletion.CASCADE, to='course.campus'),
            preserve_default=False,
        ),
    ]
