# Generated by Django 3.1.5 on 2021-01-28 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_institution_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='permisisons',
            field=models.ManyToManyField(through='users.UserPermision', to='users.Permission'),
        ),
    ]
