# Generated by Django 3.1.5 on 2021-01-28 06:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_permisisons'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='users.role'),
            preserve_default=False,
        ),
    ]
