# Generated by Django 3.1.5 on 2021-02-03 16:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('scholar', '0007_auto_20210128_1826'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalAppointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_medical_appointment', models.DateField()),
                ('consulting_room', models.CharField(max_length=6)),
                ('date_results', models.DateField()),
                ('results', models.TextField()),
                ('status_appointment', models.BooleanField()),
                ('status_patient', models.BooleanField()),
                ('scholar', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='scholar.scholar')),
            ],
        ),
    ]
